Refactor tokenizer usage in dataset_utils.py
1. issues encountered
   ```
  File "/app/TensorRT-Model-Optimizer/examples/llm_ptq/hf_ptq.py", line 146, in make_calib_dataloader
    calib_dataloader = get_dataset_dataloader(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/modelopt/torch/utils/dataset_utils.py", line 217, in get_dataset_dataloader
    batch_encoded = tokenizer.batch_encode_plus(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py", line 1291, in __getattr__
    raise AttributeError(f"{self.__class__.__name__} has no attribute {key}")
AttributeError: Qwen2Tokenizer has no attribute batch_encode_plus. Did you mean: '_encode_plus'?
   ```

2. `batch_encode_plus` was deprecated, it's recommended to to `tokenizer(...)`

Signed-off-by: jiyzhang <jiyongzhang@gmail.com>